services:
  # ---------------- Frontend ----------------
  paddock-mier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paddock
    working_dir: /app
    ports:
      - "5173:80"
    environment:
      VITE_API_KEY:
